name: delete old versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 5'

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: lower registry name
        run: |
          echo "REGISTRY=${REGISTRY,,}" >>"${GITHUB_ENV}"

      - name: delete
        uses: dylanratcliffe/delete-untagged-containers@main
        with:
          package_name: ${{ github.event.repository.name }}
          token: ${{ secrets.GITHUB_TOKEN }}

