name: Image

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

env:
  REGISTRY: ghcr.io/${{ github.repository_owner }}
  IMAGE_NAME: ${{ github.event.repository.name }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: lower registry name
        run: |
          echo "REGISTRY=${REGISTRY,,}" >>"${GITHUB_ENV}"

      - name: get current Fedora version
        run: |
          echo "FEDORA_VERSION=$(curl https://builds.coreos.fedoraproject.org/streams/stable.json | jq -r .architectures.aarch64.artifacts.metal.release | awk -F. '{ print $1; }')" >>"${GITHUB_ENV}"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          Containerfiles: ./Containerfile
          platforms: "linux/aarch64"
          build-args:
            version=${{ env.FEDORA_VERSION }}

      - name: Publish Image
        uses: redhat-actions/push-to-registry@v2
        with:
         image: ${{ env.IMAGE_NAME }}
         tags: latest
         registry: ${{ env.REGISTRY }}
         username: ${{ github.repository_owner }}
         password: ${{ secrets.GITHUB_TOKEN }}

